## STAGE 1: Use a temporary container to build QEMU, LLVM and GDB for Cambridge
FROM ubuntu:22.04 AS cheri-builder

# Set non-interactive frontend for apt to skip any user confirmations
ENV DEBIAN_FRONTEND=noninteractive

#Install build dependencies
RUN apt update -y && \
    apt upgrade -y && \
    apt install -y \
    git \
    cmake \
    ninja-build \
    gperf \
    ccache \
    dfu-util \
    device-tree-compiler \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-tk \
    python3-wheel \
    xz-utils \
    file \
    make \
    gcc \
    gcc-multilib \
    g++-multilib \
    libsdl2-dev \
    libmagic1 \
    python3-venv \
    autoconf \
    automake \
    libtool \
    pkg-config \
    clang \
    bison \
    samba \
    flex \
    texinfo \
    time \
    libglib2.0-dev \
    libpixman-1-dev \
    libarchive-dev \
    libarchive-tools \
    libbz2-dev \
    libattr1-dev \
    libcap-ng-dev \
    libexpat1-dev \
    libgmp-dev \
    libmpfr-dev \
    libmpc-dev \
    libncurses-dev \
    libdebuginfod-dev \
    bzip2

# Create a non-root user - cheribuild causes fatal error if run as root
RUN useradd -m -s /bin/bash builder && echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/builder
USER builder

# Get the cheribuild script and build the freestanding-cheri-sdk
RUN git clone https://github.com/CTSRD-CHERI/cheribuild.git && \
    cd cheribuild && \
    ./cheribuild.py freestanding-cheri-sdk -d


## STAGE 2: Create an image to that has only the cheribuild binaries
FROM ubuntu:22.04 AS cheri-runner

ENV DEBIAN_FRONTEND=noninteractive

# Install runner dependencies
RUN apt update -y && \
    apt upgrade -y && \
    apt install -y \
    git \
    cmake \
    ninja-build \
    gperf \
    ccache \
    dfu-util \
    device-tree-compiler \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-tk \
    python3-wheel \
    xz-utils \
    file \
    make \
    gcc \
    gcc-multilib \
    g++-multilib \
    libsdl2-dev \
    libmagic1 \
    python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a non-root user - cheribuild causes fatal error if run as root
RUN useradd -m -s /bin/bash builder && echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Copy the cheri SDK tools into the runner
RUN mkdir -p /opt/cheri-tools/
COPY --from=cheri-builder --chown=builder:builder /home/builder/cheri/output /opt/cheri-tools/cheri
RUN chown builder:builder /opt/cheri-tools

WORKDIR /home/builder
USER builder

# Clone the CHERI-Zephyr release
RUN git clone --branch CHERI-RISCV64-v2.0 --depth 1 https://github.com/CHERI-Alliance/CHERI-zephyr.git zephyr

# Install west
RUN python3 -m venv .venv && . .venv/bin/activate && \
    pip install --no-cache-dir west && \
    west init -l zephyr && \
    west update --narrow --fetch-opt=--depth=1 && \
    west zephyr-export && \
    pip install --no-cache-dir -r zephyr/scripts/requirements.txt

ENV ZEPHYR_TOOLCHAIN_VARIANT=llvm-cheri
ENV LLVM_CHERI_TOOLCHAIN_PATH=/opt/cheri-tools/cheri/sdk
ENV QEMU_BIN_PATH=/opt/cheri-tools/cheri/sdk/bin

CMD ["bash"]
