## STAGE 1: Use a temporary container to build QEMU, LLVM and GDB for Cambridge
FROM ubuntu:24.04 AS cheri-builder

# Set non-interactive frontend for apt to skip any user confirmations
ENV DEBIAN_FRONTEND=noninteractive

#Install build dependencies
RUN apt update -y && \
    apt upgrade -y && \
    apt install -y \
    git \
    cmake \
    ninja-build \
    gperf \
    ccache \
    dfu-util \
    device-tree-compiler \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-tk \
    python3-wheel \
    xz-utils \
    file \
    make \
    gcc \
    libsdl2-dev \
    libmagic1 \
    python3-venv \
    autoconf \
    automake \
    libtool \
    pkg-config \
    clang \
    bison \
    samba \
    flex \
    texinfo \
    time \
    libglib2.0-dev \
    libpixman-1-dev \
    libarchive-dev \
    libarchive-tools \
    libbz2-dev \
    libattr1-dev \
    libcap-ng-dev \
    libexpat1-dev \
    libgmp-dev \
    libmpfr-dev \
    libmpc-dev \
    libncurses-dev \
    libdebuginfod-dev \
    bzip2

# Create a non-root user
RUN useradd -m -s /bin/bash builder && echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/builder
USER builder

# Build Codasip QEMU
RUN git clone --no-checkout --recurse-submodules --branch codasip-cheri-riscv_v3 https://github.com/CHERI-Alliance/qemu.git qemu-codasip && \
    cd qemu-codasip && \
    git checkout 2a2e882b && \
    mkdir build install && \
    cd build && \
    ../configure \
        --prefix=/home/builder/qemu-codasip/install \
        --target-list="riscv32cheri-softmmu riscv64cheri-softmmu" \
        --disable-gtk --audio-drv-list="" --disable-brlapi --disable-libiscsi \
        --disable-libnfs --disable-rbd --disable-sdl --disable-snappy \
        --disable-vnc --disable-vnc-jpeg --disable-vnc-sasl --disable-l2tpv3 \
        --disable-oss --disable-alsa --disable-tpm --disable-werror --meson=git && \
     ninja && \
     ninja install && \
     cd ~/

# Build Codasip GDB
RUN git clone --no-checkout --recurse-submodules --branch codasip-cheri-riscv https://github.com/CHERI-Alliance/gdb.git gdb-codasip && \
    cd gdb-codasip && \
    git checkout df929d4d && \
    mkdir build install && \   
    cd build && \
    ../configure \
        --target=riscv64-unknown-elf \
        --prefix=/home/builder/gdb-codasip/install && \
    make -j$(nproc) && \
    make install &&\
    cd ~/

## STAGE 2: Create an image to that has only the cheribuild binaries
FROM ubuntu:24.04 AS cheri-runner

ENV DEBIAN_FRONTEND=noninteractive

# Install runner dependencies
RUN apt update -y && \
    apt upgrade -y && \
    apt install -y --no-install-recommends \
    git \
    cmake \
    ninja-build \
    gperf \
    ccache \
    dfu-util \
    device-tree-compiler \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-tk \
    python3-wheel \
    xz-utils \
    file \
    make \
    gcc \
    libsdl2-dev \
    libmagic1 \
    libpixman-1-dev \
    python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a non-root user - cheribuild causes fatal error if run as root
RUN useradd -m -s /bin/bash builder && echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Copy the cheri SDK tools into the runner
RUN mkdir -p /opt/cheri-tools/
COPY --from=cheri-builder /home/builder/qemu-codasip/install /opt/cheri-tools/qemu-codasip
COPY --from=capablehub/cheri-ca-llvm:17-riscv64-678272e --chown=builder:builder /root/llvm-cheri/install /opt/cheri-tools/llvm-cheri-codasip
COPY --from=cheri-builder /home/builder/gdb-codasip/install  /opt/cheri-tools/gdb-codasip 
RUN chown builder:builder /opt/cheri-tools

WORKDIR /home/builder
USER builder

# Clone the CHERI-Zephyr release & Install west
RUN git clone --branch CHERI-RISCV64-v2.0 --depth 1 https://github.com/CHERI-Alliance/CHERI-zephyr.git zephyr && \
    python3 -m venv .venv && . .venv/bin/activate && \
    pip install --no-cache-dir west && \
    west init -l zephyr && \
    west update --narrow --fetch-opt=--depth=1 && \
    west zephyr-export && \
    pip install --no-cache-dir -r zephyr/scripts/requirements.txt && \
    find . -name ".git" -type d -exec rm -rf {} +

ENV ZEPHYR_TOOLCHAIN_VARIANT=llvm-cheri
ENV LLVM_CHERI_TOOLCHAIN_PATH=/opt/cheri-tools/llvm-cheri-codasip
ENV QEMU_BIN_PATH=/opt/cheri-tools/qemu-codasip/bin
RUN echo "source ~/.venv/bin/activate" >> ~/.bashrc

CMD ["bash"]
