FROM ghcr.io/anyvm-org/anyvm:v0.0.5

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -yy \
    curl && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

ENTRYPOINT [ "/bin/bash", "-c" ]
